### ISSUE TITLE
Suggestion: It would be neat to be able to input a list of runs to be skipped on the start_pipeline() function

### ISSUE THREAD

**Issue by RealAurio** [ATTPC/Spyral#163]
In my particular case, I am having trouble with a bunch of runs, which I am skipping manually for now. However, I think it could be useful to be able to input a list of run numbers into the start_pipeline() function that, for whatever reason, need to be skipped by spyral.

One of the reasons you may want to skip runs is because something is wrong with their merging, so they make spyral crash, preventing the rest of the runs to be processed.

Another reason is that maybe the conditions changed for a set of runs, so that they need to be processed separately with different spyral parameters.

**Comment by gwm17** [comment]
Done as of v0.11.0, see the [start_pipeline](https://attpc.github.io/Spyral/api/core/pipeline/#spyral.core.pipeline.start_pipeline)
