### ISSUE TITLE
Logs should display run number

### ISSUE THREAD

**Issue by turinath** [ATTPC/Spyral#177]
When Spyral reports an error, it is often confusing to track down which run the error occurs in since that information is not included in the process log. It would be nice if the run numbers were included in each log message, for both successful runs and runs where errors occur.

**Comment by gwm17** [comment]
So looking at this, we can't do this everywhere. Logging isn't exclusively used in phases, and in many places logging may be called from code which has no knowledge of runs or run numbers. I updated some of the existing logs to better report run numbers (i.e. now the end of phase messages report run numbers), but I don't think we can easily blanket implement run numbers as part of logging, if that was the idea

**Comment by gwm17** [comment]
Done, waiting to be PR'd
