### ISSUE TITLE
Saturated Pads Produce Multiple Peaks

### ISSUE THREAD

**Issue by turinath** [ATTPC/Spyral#3]
When we find a pad whose signal has been saturated (~4100 adc height), it creates a plateau in the signal which then produces multiple peaks in this region. 

Ex: Run 348, Event 146674, Trace 43

**Comment by turinath** [comment]
For now it seems like completely removing the points generated from saturated traces is the right move. We will have to look into removing the points at the level of the point cloud as to not interfere with cross-talk removal. Keeping the unadjusted amplitude of the trace as an attribute in the Peak class is important for keeping track of saturated signals.

**Comment by gwm17** [comment]
Marking this as closed. Saturated signals are way more complicated then we thought and the feature_saturation is attempting to resolve them!
